### ISSUE TITLE
merge with perlbrew

### ISSUE THREAD

**Issue by nichtich** [dex4er/perluse#1]
Why did you create another wrapper-wrapper instead of just improving the original? This script could better be shipped together with perlbrew, couldn't it?

**Comment by dex4er** [comment]
I'm planning to add a support for enabling system perl with local::lib and other instantions, ie. MacPorts.

But yes, some of features could be merged to perlbrew.

**Comment by dex4er** [comment]
In perlbrew we can do `perlbrew exec --with perl-5.30.1 perl -E 'say $^V'` so some functionality exists there already.

Still `perluse` makes sense because it doesn't require perlbrew to be integrated into `bashrc` as it loads it only when required.
